name: 'discord-ipfs-action'
description: 'Send a rich message to a Discord webhook.'
branding:
  color: 'purple'
  icon: 'message-square'
inputs:
  webhook:
    description: 'Discord webhook URL'
    required: true
  cid:
    description: 'CID of the deployment'
    required: true
  commit:
    description: 'Github commit that triggered this deployment'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
